### ISSUE TITLE
How to extend a graph

### ISSUE THREAD

**Issue by jonhilgart22** [IAAR-Shanghai/PGRAG#1]
If I've generated a graph, what's the best way to extend the graph as new documents come in?

**Comment by siminniu** [comment]
Thank you for your interest in our work!

Regarding your question, you only need to place the new set of documents into a new directory, for example:
```python
raw_news_files_dir = 'data/raw_news/new_batch'
```

Then, execute the following code:
```python
from pgrag.mindmap_generator import MindmapGeneration

mindmap_generation = MindmapGeneration(
    model_name, 
    num_threads, 
    raw_news_files_dir, 
    title_files_dir, 
    fcis_files_dir, 
    mindmaps_str_files_dir, 
    mindmaps_json_files_dir
)
mindmap_generation.execute()
```

For each document in the new batch, we independently extract FCIs and transform them into a separate mind map. This hierarchical indexing process is independent and can be incrementally added to the existing PG database.

Thank you for your question. We will further enhance the user experience in the new version, including optimizing the operation of batch updates to the database.

Thanks again for your support!
