### ISSUE TITLE
文件存储地址出错

### ISSUE THREAD

**Issue by 540930** [IAAR-Shanghai/PGRAG#4]
作者您好
![屏幕截图 2024-07-23 132832](https://github.com/user-attachments/assets/80e9dc45-7f7b-4db3-84be-1fb6741f4233)
最下面是：[Errno 2] No such file or directory: 'E:\\浏览器下载\\PGRAG-main\\PGRAG-main\\data\\pg_gen\\batch0\\textToVerificationText\\2022-01-01.txt\\2022-01-01.txt'
为什会在文本文件下又创建一个呢，我把地址打印出来您看下
![屏幕截图 2024-07-23 132650](https://github.com/user-attachments/assets/4f14d783-a599-49ea-b671-acf3a124feda)
![屏幕截图 2024-07-23 132606](https://github.com/user-attachments/assets/7d6098d3-d4f5-4a44-bae1-e85cc27d28af)

**Comment by siminniu** [comment]
您好！请问这个问题最终解决了嘛，是哪里的问题呀

**Comment by Goye-Cassini** [comment]
> 作者您好 ![屏幕截图 2024-07-23 132832](https://private-user-images.githubusercontent.com/154941640/351196657-80e9dc45-7f7b-4db3-84be-1fb6741f4233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTAwMTcsIm5iZiI6MTcyNjY0OTcxNywicGF0aCI6Ii8xNTQ5NDE2NDAvMzUxMTk2NjU3LTgwZTlkYzQ1LTdmN2ItNGRiMy04NGJlLTFmYjY3NDFmNDIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2NjNjZjZTZmZjJlNTk1MTU5YTdiMTk3NDBkYTlhNDhhMmVkZWZhZDY3NTAwYzkzZGFlYTBiYzFhNjlhMGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UvssvUf3pS1_b-GE3YkcoY9hZ1P8cswWIuazoXOLQWk) 最下面是：[Errno 2] No such file or directory: 'E:\浏览器下载\PGRAG-main\PGRAG-main\data\pg_gen\batch0\textToVerificationText\2022-01-01.txt\2022-01-01.txt' 为什会在文本文件下又创建一个呢，我把地址打印出来您看下 ![屏幕截图 2024-07-23 132650](https://private-user-images.githubusercontent.com/154941640/351197096-4f14d783-a599-49ea-b671-acf3a124feda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTAwMTcsIm5iZiI6MTcyNjY0OTcxNywicGF0aCI6Ii8xNTQ5NDE2NDAvMzUxMTk3MDk2LTRmMTRkNzgzLWE1OTktNDllYS1iNjcxLWFjZjNhMTI0ZmVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWMzYzg4ZmFiNTcwZThlODhkNzM1OWI3MGI2NGVlOTkzMDk2N2E1MjQ0NTgyMmE0NTA2OWUyNzU1ODQ2YzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GIrqrRtch4D27qOsO7fzhQAV6ERBA5V4a7qMBLTR95I) ![屏幕截图 2024-07-23 132606](https://private-user-images.githubusercontent.com/154941640/351197107-7d6098d3-d4f5-4a44-bae1-e85cc27d28af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTAwMTcsIm5iZiI6MTcyNjY0OTcxNywicGF0aCI6Ii8xNTQ5NDE2NDAvMzUxMTk3MTA3LTdkNjA5OGQzLWQ0ZjUtNGE0NC1iYWUxLWU4NWNjMjdkMjhhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODFmMmNlNWFlNjA2YzU2OTdhZTBkYTA0NzUyNTBlNzQ2MDMwZjYxNzQ0ZjU5Y2JiOWMzYWFiNDBkMTU1YmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92RVOWK9CiyC6m3fU786gh20QJcc7pwrWfxWplq8v-A)

请问您最后是如何解决的? 将fcis_files_dir改为文件路径不带路径下的文件名可以吗？

**Comment by siminniu** [comment]
您好，或许您可以尝试一下更新后的项目，看看是否仍会出现此问题
