### ISSUE TITLE
伪图构建所用数据问题？

### ISSUE THREAD

**Issue by 540930** [IAAR-Shanghai/PGRAG#5]
作者您好！请问您们在构建伪图所用的新闻数据是什么？应该是和检索时用的CRUD_RAG文件下的3个json文件内容相对应的txt文件呀？

**Comment by siminniu** [comment]
您好！我们所用的原始文本库，在CRUD_RAG中的data目录下


---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2024年07月24日 19:05 收件人  ***@***.***> 抄送至  ***@***.***> 主题  [IAAR-Shanghai/PGRAG] 伪图构建所用数据问题？ (Issue #5)  

作者您好！请问您们在构建伪图所用的新闻数据是什么？应该是和检索时用的CRUD_RAG文件下的3个json文件内容相对应的txt文件呀？
