### ISSUE TITLE
嵌入向量维度

### ISSUE THREAD

**Issue by 540930** [IAAR-Shanghai/PGRAG#6]
请问这个1024可以改吗？CREATE VECTOR INDEX topic-embeddings IF NOT EXISTS
FOR (m:Topic)
ON m.主题嵌入
OPTIONS {indexConfig: {
 `vector.dimensions`: 1024,
 `vector.similarity_function`: 'cosine'
}}

CREATE VECTOR INDEX fact-embeddings IF NOT EXISTS
FOR (m:Content)
ON m.路径嵌入
OPTIONS {indexConfig: {
 `vector.dimensions`: 1024,
 `vector.similarity_function`: 'cosine'
}}

**Comment by siminniu** [comment]
可以根据您所用的嵌入模型生成的嵌入纬度去改的，例如生成的是512维的嵌入向量，则建立索引的时候此处也改为512


---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2024年07月25日 10:46 收件人  ***@***.***> 抄送至  ***@***.***> 主题  [IAAR-Shanghai/PGRAG] 嵌入向量维度 (Issue #6)  

请问这个1024可以改吗？CREATE VECTOR INDEX topic-embeddings IF NOT EXISTS
 FOR (m:Topic)
 ON m.主题嵌入
 OPTIONS {indexConfig: {
 vector.dimensions: 1024,
 vector.similarity_function: 'cosine'
 }}
CREATE VECTOR INDEX fact-embeddings IF NOT EXISTS
 FOR (m:Content)
 ON m.路径嵌入
 OPTIONS {indexConfig: {
 vector.dimensions: 1024,
 vector.similarity_function: 'cosine'
 }}

**Comment by 540930** [comment]
好的！谢谢！

**Comment by siminniu** [comment]
客气啦


---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2024年07月25日 10:52 收件人  ***@***.***> 抄送至  ***@***.***>***@***.***> 主题  Re: [IAAR-Shanghai/PGRAG] 嵌入向量维度 (Issue #6)  

好的！谢谢！
