### ISSUE TITLE
关于baseline的问题

### ISSUE THREAD

**Issue by jeremycp3** [IAAR-Shanghai/PGRAG#7]
你好，请问关于DPR在这个数据集上实现的代码在哪里可以找到呢？

**Comment by siminniu** [comment]
您好，感谢您对本项目的关注！这个代码的位置在：https://github.com/IAAR-Shanghai/CRUD_RAG/blob/main/src/retrievers/base.py

**Comment by jeremycp3** [comment]
谢谢，我已经找到了

**Comment by siminniu** [comment]
客气啦
