### ISSUE TITLE
 How to generate question files

### ISSUE THREAD

**Issue by rkdlight** [IAAR-Shanghai/PGRAG#8]
Hello! Please tell me how I should generate files like https://github.com/IAAR-Shanghai/PGRAG/blob/main/pgrag/data/eval/eval_data_with_qe_and_qdse_example.json
Are there any ready-made functions for this? and what does qdse mean?

**Comment by 694040837** [comment]
> Hello! Please tell me how I should generate files like https://github.com/IAAR-Shanghai/PGRAG/blob/main/pgrag/data/eval/eval_data_with_qe_and_qdse_example.json Are there any ready-made functions for this? and what does qdse mean?

hello! I also meet this problem.. Do you have answer now?

**Comment by rkdlight** [comment]
> > Hello! Please tell me how I should generate files like https://github.com/IAAR-Shanghai/PGRAG/blob/main/pgrag/data/eval/eval_data_with_qe_and_qdse_example.json Are there any ready-made functions for this? and what does qdse mean?
> 
> hello! I also meet this problem.. Do you have answer now?

Hello! I'm now just testing this code with only one classic embedding. I still don't understand why we need the second embedding question

**Comment by rkdlight** [comment]
> hello! I also meet this problem.. Do you have answer now?

Eureka! I just realized what it all means!) QE - query embedding, QDSE - query deconstruction split embedding. We need to write a function that will parse the request into topics; there is a prompt for this in the repository. And then receive an array of embeddings for each received topic from the user’s request. 

UPD: This repository already has such a function. https://github.com/IAAR-Shanghai/PGRAG/blob/main/pgrag/llms/base.py#L146

This is what it means to approach a question after some time with new thoughts.

**Comment by 694040837** [comment]
Nice bro. Thanks for your reply! I will try.
